#
# --------------------------
# NERDTree
# --------------------------
# 
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree', 'NERDTreeToggle']
hook_add = '''
'''
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
hook_add = '''
'''
