# 
# FZF
#
# - https://qiita.com/Sa2Knight/items/6635af9fc648a5431685
# - https://meteora.work/vim-dein-fzf
[[plugins]]
repo = "junegunn/fzf.vim"
hook_add = '''
   call LoadSource('default/fzf.vim')
'''
[[plugins]]
repo = "junegunn/fzf"
build = 'cd ~/.shellter/var/repo/fzf && ./install'
[[plugins]]
repo = "glidenote/memolist.vim"
hook_add = '''
   let g:memolist_path = "~/MyDrive/Memo"
   nnoremap <Leader>mn  :MemoNew<CR>
   nnoremap <Leader>ml  :MemoList<CR>
   nnoremap <Leader>mg  :MemoGrep<CR>
'''
