# 
# FZF
#
# - https://qiita.com/Sa2Knight/items/6635af9fc648a5431685
# - https://meteora.work/vim-dein-fzf
[[plugins]]
repo = "junegunn/fzf.vim"
[[plugins]]
repo = "junegunn/fzf"
build = './install --all'
hook_add = '''
    call LoadSource('default/fzf.vim')
'''
